## 向量枚举

In [1]:
import numpy as np

In [2]:
def findUnique(inputMat):
    output = []
    for row in range(inputMat.shape[0]):
        presentRow = list(inputMat[row])
        if presentRow not in output:
            output.append(presentRow)
    output = np.array(output)
    return output

In [3]:
x = np.array([[1., 2., 3.], [4., 5., 6.],[1., 2., 3.], [4., 5., 6.]])
print(findUnique(x))

[[1. 2. 3.]
 [4. 5. 6.]]


## 数组生成与统计

In [4]:
def generateStats(T):
    data = np.random.randn(T)
    output = []
    for startIndex in range(T - 3 + 1):
        output.append(data[startIndex: startIndex + 3])
    output = np.array(output)
    return output

def calculateStats(intputMat):
    matMean = np.mean(intputMat, axis=0)
    matVar = np.var(intputMat, axis=0)
    matCovar = []
    for firstCol in range(3):
        for secondCol in range(3):
            if firstCol != secondCol and firstCol < secondCol:
                covar = np.sum((matMean[firstCol] - inputMat[:, firstCol]) * (matMean[secondCol] - inputMat[:, secondCol])) / inputMat.shape[0]
                matCovar.append([str(firstCol) + "-" + str(secondCol) + "协方差", covar])
    matCovar = np.array(matCovar)
    return matMean, matVar, matCovar

In [5]:
inputMat = generateStats(T=10)
matMean, matVar, matCovar = calculateStats(inputMat)
print("数组:\n{0}\n\n 均值:\n{1}\n\n 方差:\n{2}\n\n 协方差:\n{3}".format(inputMat, matMean, matVar, matCovar))

数组:
[[-0.93520333  0.59418955 -1.88957761]
 [ 0.59418955 -1.88957761  0.65216644]
 [-1.88957761  0.65216644  0.29621417]
 [ 0.65216644  0.29621417 -0.91892941]
 [ 0.29621417 -0.91892941  0.65946127]
 [-0.91892941  0.65946127  0.55324251]
 [ 0.65946127  0.55324251 -0.21372558]
 [ 0.55324251 -0.21372558  0.70788642]]

 均值:
[-0.12355455 -0.03336983 -0.01915772]

 方差:
[0.84681323 0.75734958 0.77660135]

 协方差:
[['0-1协方差' '-0.4227719715499682']
 ['0-2协方差' '0.11429238345787136']
 ['1-2协方差' '-0.36873894038942234']]


In [10]:
a = [0] * 3
for i in range(10000):
    a[np.random.randint(0, 3)] += 1
print(a)

[3308, 3376, 3316]


## 数组生成与排序

In [ ]:
def matGenerate_Sort(rows=1000, cols=50, range=[0, 3]):
    output = np.random.randint(range[0], range[1], (rows, cols))
    output = output[np.lexsort((-output[:,1], output[:,0]))]
    return output

def sortbycols(data, cols, descending)