In [94]:
import numpy as np
from numpy.random import randn
from numpy.random import randint

### 作业1 找出数组所有不同行

In [81]:
def get_keys(d, value):
    return [k for k,v in d.items() if all(v == value)]

def d_array(x):
    a=0
    d=dict()
    for i in range(len(x)):
        if len(get_keys(d,x[i]))==0:
            d[a]=x[i]
            a=a+1
    return d.values()

a = np.array([[1., 2., 3.], [4., 5., 6.],[1., 2., 3.], [4., 5., 6.]])
b = np.array([[1., 2., 3.], [4., 5., 6.],[7., 8., 9.], [4., 5., 6.],[10,11,12]])
print(d_array(a))
print(d_array(b))

dict_values([array([1., 2., 3.]), array([4., 5., 6.])])
dict_values([array([1., 2., 3.]), array([4., 5., 6.]), array([7., 8., 9.]), array([10., 11., 12.])])


### 作业2

In [90]:
def Create_Z(T):
    t=randn(T)
    print(t)
    new_t=[]
    for i in range(T-2):
        new_t.append(t[i:i+3])
    new_t=np.array(new_t).reshape(T-2,3)
    return new_t
def Calculation(Z):
    Z=Z.T
    for i in range(len(Z)):
        print(f'第{i+1}列的样本均值：',np.mean(Z[i]),'方差：',np.var(Z[i]),'协方差：',np.cov(Z[i]))

(a)

In [92]:
##a
Z=Create_Z(6)

[ 2.01907465  2.34423072  0.24868562 -0.23386229 -0.01614449  1.24730766]
[[ 2.01907465  2.34423072  0.24868562]
 [ 2.34423072  0.24868562 -0.23386229]
 [ 0.24868562 -0.23386229 -0.01614449]
 [-0.23386229 -0.01614449  1.24730766]]


(b)

In [93]:
##b
Calculation(Z)

第1列的样本均值： 1.0945321733262483 方差： 1.2241533773027649 协方差： 1.6322045030703531
第2列的样本均值： 0.5857273873351759 方差： 1.0599770329685139 协方差： 1.4133027106246854
第3列的样本均值： 0.3114966219625984 方差： 0.3211131414429337 协方差： 0.4281508552572449


### 作业3

(a)

In [176]:
#a
x=[]
for i in range(50000):
    x.append(randint(0,3))
x=np.array(x).reshape(1000,50)
print('原始数组',x)
##第一列递增
a = x[np.argsort(x[:,0])]
a=-a
b=-a[np.argsort(a[:,0])]
print('第一列递增',b)
##第二列递减
c=b[np.argsort(b[:,1])]
print('第二列递减',c)

原始数组 [[0 2 1 ... 1 2 1]
 [2 1 2 ... 0 1 0]
 [1 2 0 ... 0 0 0]
 ...
 [1 1 1 ... 1 1 0]
 [1 2 1 ... 0 2 1]
 [0 2 2 ... 1 1 2]]
第一列递增 [[2 0 0 ... 1 0 2]
 [2 0 1 ... 1 2 0]
 [2 0 1 ... 0 2 0]
 ...
 [0 2 2 ... 0 0 0]
 [0 0 1 ... 2 0 2]
 [0 2 1 ... 1 2 1]]
第二列递减 [[2 0 0 ... 1 0 2]
 [2 0 1 ... 0 0 0]
 [2 0 0 ... 1 2 1]
 ...
 [0 2 1 ... 2 0 1]
 [0 2 0 ... 1 2 2]
 [0 2 1 ... 1 2 1]]


(b)

In [370]:
##b
def sortbycols(data,cols,descending):
    c=[]
    if type(cols)==int:
        c.append(cols)
    else :
        c=c+cols
    d=[]
    if type(descending)==bool:
        d.append(descending)
    else :
        d=d+descending
    if len(d)==1:
        if d[0]==True:
             for i in c:
                    data = data[np.argsort(data[:,i])]
    elif len(d)==len(c):
        for i in range(len(c)):
            if d[i]==True:
                data = data[np.argsort(data[:,c[i]])]
    return data

In [372]:
x = np.array([[1., 2., 3.], [4., 5., 6.],[3., 9., 3.], [4., 5., 6.]])
print(sortbycols(x,0,False))
print(sortbycols(x,0,True))
print(sortbycols(x,[0,1],[True,False]))
print(sortbycols(x,[0,1],[False,False]))
print(sortbycols(x,[0,1],[False,True]))

[[1. 2. 3.]
 [4. 5. 6.]
 [3. 9. 3.]
 [4. 5. 6.]]
[[1. 2. 3.]
 [3. 9. 3.]
 [4. 5. 6.]
 [4. 5. 6.]]
[[1. 2. 3.]
 [3. 9. 3.]
 [4. 5. 6.]
 [4. 5. 6.]]
[[1. 2. 3.]
 [4. 5. 6.]
 [3. 9. 3.]
 [4. 5. 6.]]
[[1. 2. 3.]
 [4. 5. 6.]
 [4. 5. 6.]
 [3. 9. 3.]]


### 作业4

In [374]:
def fv(rate,nper,pmt,pv):
    return np.fv(rate,nper,pmt,pv)
##rate:存款/贷款每期的利率
##nper：存款/贷款期数
##pmt：存款/贷款每期支付的金额
##fv：存款/贷款终值，如果是贷款，终值为0；如果是存款，终值为本息

In [375]:
def pv(rate,nper,pmt,fv):
    return np.pv(rate,nper,pmt,fv)
##rate:存款/贷款每期的利率
##nper：存款/贷款期数
##pmt：存款/贷款每期支付的金额
##fv：存款/贷款终值，如果是贷款，终值为0；如果是存款，终值为本息和

In [378]:
def nper(rate,pmt,pv,fv):
    return np.nper(rate,pmt,pv,fv)
##rate:存款/贷款每期的利率
##pmt：存款/贷款每期支付的金额
##pv：存款/贷款金额
##fv：存款/贷款终值，如果是贷款，终值为0；如果是存款，终值为本息和

In [380]:
def pmt(rate,nper,pv):
    return np.pmt(rate,nper,pv)
##rate:存款/贷款每期的利率
##nper：存款/贷款期数
##pv：存款/贷款金额

In [ ]:
def rate(nper, pmt, pv, fv):
    return np.rate(nper, pmt, pv, fv)
##nper:贷款年数
##pmt:每期投入
##pv:现值
##fv:终值